[toolchain]
channel = "nightly-2026-10-02"
components = ["rust-src", "rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown", "aarch64-linux-android", "armv7-linux-androideabi", "x86_64-linux-android", "i686-linux-android"]
profile = "minimal"
